#!/bin/env python

import os
import sys

ALIAS = {
        'alias0' : 'hostname0',
}

def print_usage():
    print "USAGE\n" \
          "    $0 [-l] <hostname or alias>\n" \
          "OPTIONS\n" \
          "    -l  list hostname alias"

def list_alias():
    print "%-10s %s" % ('ALIAS', 'HOSTNAME')
    for k, v in ALIAS.items():
        print "%-10s %s" % (k, v)

def connect(key):
    hostname = ALIAS.has_key(key) and ALIAS[key] or key
    os.system("ssh %s"%(hostname))

if __name__ == '__main__':
    if len(sys.argv) < 2:
        print_usage()
    elif sys.argv[1] == '-l':
        list_alias()
    else:
        connect(sys.argv[1])
