#
# ~/.bashrc
#

[[ -f /etc/bashrc ]] && source /etc/bashrc

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias ll='ls -l'
alias la='ls -a'
alias lla='ls -la'
alias svi='sudo vi'
alias scat='sudo cat'
alias sfind='sudo find'
alias glog='git log --pretty=format:"%C(yellow)%H %C(blue)%an%C(red) %s %C(reset)" --stat'
alias glogo='git log --pretty=oneline'
alias glogs='git log --pretty=short'
alias ta='tmux attach -d -t'
alias tls='tmux ls'

PATH=$PATH:~/.usr/bin/
export PATh

LD_LIBRARY_PATH=$HOME/.usr/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
