# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
PATH=/sbin:/bin:$PATH
PATH=$HOME/usr/bin/ccover/bin:$PATH
PATH=$HOME/.BCloud/bin:$PATH
PATH=$HOME/scmtool/usr/bin:$PATH
PATH=$HOME/.jumbo/bin:$PATH

LD_LIBRARY_PATH=$HOME/.jumbo/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH

PATH=$HOME/.BCloud/bin:$PATH
export PATH
