# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
# config in bash_common and bashrc instead of heresource "$HOME/.cargo/env"
