# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs

PATH=$HOME/usr/bin/:/sbin:/bin:$PATH
export PATH

LD_LIBRARY_PATH=$HOME/usr/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
